import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Circle,
  Image,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  MoreVertical,
  Plus,
  Pencil,
  Settings,
  Trash,
  Trash2,
  User,
  User2Icon,
  UserX2Icon,
  X,
  ChevronDown,
  Briefcase,
  Monitor,
  Star,
  Sparkles,
  Copy,
  Eye,
  Minus,
  LoaderCircle,
  CircleCheck,
  CircleX,
  ArrowLeftToLine,
  ArrowRightToLine,
  Phone,
  MessageSquareText,
  List,
  LayoutGrid,
  Dot,
  Building,
  House,
  GraduationCap,
  Keyboard,
  Lightbulb,
  EllipsisVertical,
  Megaphone,
  Users,
  SlidersVertical,
  ClipboardMinus,
  CircleMinus,
  Flame,
  Clock3,
  Settings2,
  Menu,
  ShoppingCart,
  Mail,
  Lock,
  ShieldMinus,
  Info,
  FlagTriangleRight,
  SquarePlay,
  Tag,
  CircleDot,
  ArrowDownToLine,
  Share2,
  Wallet,
  FilePenLine,
  FileSpreadsheet,
  LogOut,
  ChevronsUpDown,
  Tally3,
  Filter,
  ClipboardList,
  ArrowUpDown,
  Sheet,
  Package,
  Shield,
  UserCog,
  CirclePlus,
  UsersRound,
  CalendarCheck,
  Timer,
  Zap,
  LockKeyhole,
  ChevronsLeft,
  ChevronsRight,
  Globe,
  Facebook,
  Instagram,
  Twitter,
  Youtube,
  Linkedin,
  CircleCheckBig,
  Calendar,
  MapIcon,
  MoveUp,
  MoveDown,
  Download,
  Search,
  RefreshCcw,
  ThumbsUp,
  ThumbsDown,
  RefreshCw,
  BrainCircuit,
  Languages,
  Upload,
  FileSearch2,
  SidebarClose,
  FileScan,
  UserRoundCog,
  ScanLine,
  Smartphone,
  Camera,
  LibraryBig,
  SquareChartGantt,
  PersonStanding,
  NotebookPen,
  LucideFileText,
  Bookmark,
  UserRoundCheck,
  FileUser,
  FileCheck,
  ShieldCheck,
  UserCheck,
  SearchCheck,
  Handshake,
  Presentation,
  ClipboardCheck,
  SlidersHorizontal,
  ChartNoAxesCombined,
  Target,
  ChartBar,
  FileDigit,
  Folder,
  Database,
  TicketCheck,
  Rss,
  MessageSquareQuote,
  TrendingUp,
  BadgeDollarSign,
  Newspaper,
  SearchIcon,
  Locate,
  BookMarked,
  MapPin,
  CircleDashed,
  SquareArrowOutUpRight,
  CircleAlert,
  BriefcaseBusiness,
  ChartLine,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  setting2: Settings2,
  clock3: Clock3,
  dashboard: LayoutDashboardIcon,
  menu: Menu,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronRight: ChevronRight,
  trash: Trash,
  trash2: Trash2,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  edit: Pencil,
  warning: AlertTriangle,
  user: User,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  help: HelpCircle,
  check: Check,
  arrowDown: ChevronDown,
  briefcase: Briefcase,
  monitor: Monitor,
  star: Star,
  sparkles: Sparkles,
  copy: Copy,
  views: Eye,
  StepBar: Minus,
  loaderCircle: LoaderCircle,
  circleCheck: CircleCheck,
  circleX: CircleX,
  arrayLeftToLine: ArrowLeftToLine,
  arrowRightToLine: ArrowRightToLine,
  phone: Phone,
  messageSquareText: MessageSquareText,
  list: List,
  grid: LayoutGrid,
  dot: Dot,
  building: Building,
  house: House,
  graduationCap: GraduationCap,
  keyboard: Keyboard,
  lightbulb: Lightbulb,
  colon: EllipsisVertical,
  circle: Circle,
  flame: Flame,
  flagTriangleRight: FlagTriangleRight,
  circleMinus: CircleMinus,
  megaphone: Megaphone,
  users: Users,
  slidersVertical: SlidersVertical,
  clipboardMinus: ClipboardMinus,
  cart: ShoppingCart,
  mail: Mail,
  lock: Lock,
  shieldMinus: ShieldMinus,
  info: Info,
  squarePlay: SquarePlay,
  tag: Tag,
  circleDot: CircleDot,
  arrowDownToLine: ArrowDownToLine,
  share2: Share2,
  wallet: Wallet,
  filePenLine: FilePenLine,
  fileSpreadsheet: FileSpreadsheet,
  logOut: LogOut,
  arrowUpDown: ChevronsUpDown,
  bar: Tally3,
  clipBoardList: ClipboardList,
  filter: Filter,
  clipboardList: ClipboardList,
  circlePlus: CirclePlus,
  arrowUpDown2: ArrowUpDown,
  sheet: Sheet,
  package: Package,
  shield: Shield,
  userCog: UserCog,
  groupUser: UsersRound,
  calendarCheck: CalendarCheck,
  calendar: Calendar,
  timer: Timer,
  zap: Zap,
  lockKeyHole: LockKeyhole,
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  globe: Globe,
  youtube: Youtube,
  linkedin: Linkedin,
  circleCheckBig: CircleCheckBig,
  map: MapIcon,
  save: Bookmark,
  chartLine: ChartLine,
  briefcaseBusiness: BriefcaseBusiness,
  moveUp: MoveUp,
  moveDown: MoveDown,
  download: Download,
  search: Search,
  refresh: RefreshCcw,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  brainCircuit: BrainCircuit,
  languages: Languages,
  upload: Upload,
  fileSearch2: FileSearch2,
  sidebarClose: SidebarClose,
  fileScan: FileScan,
  userRoundCog: UserRoundCog,
  scanLine: ScanLine,
  smartphone: Smartphone,
  pencil: Pencil,
  bookMark: Bookmark,
  camera: Camera,
  library: LibraryBig,
  squarechartgantt: SquareChartGantt,
  personstanding: PersonStanding,
  notebookpen: NotebookPen,
  filetext: LucideFileText,
  userRoundCheck: UserRoundCheck,
  fileUser: FileUser,
  fileCheck2: FileCheck,
  shieldCheck: ShieldCheck,
  userCheck: UserCheck,
  searchCheck: SearchCheck,
  handshake: Handshake,
  presentation: Presentation,
  clipboardCheck: ClipboardCheck,
  slidersHorizontal: SlidersHorizontal,
  chartNoaxescombined: ChartNoAxesCombined,
  target: Target,
  chartBar: ChartBar,
  fileDigit: FileDigit,
  folder: Folder,
  database: Database,
  ticket: TicketCheck,
  rss: Rss,
  response: MessageSquareQuote,
  trendingUp: TrendingUp,
  badgeDollarsign: BadgeDollarSign,
  newsPaper: Newspaper,
  searchs: SearchIcon,
  locate: Locate,
  bookMarked: BookMarked,
  mapPin: MapPin,
  circledashed: CircleDashed,
  squareArrowOutUpRight: SquareArrowOutUpRight,
  circleAlert: CircleAlert,
};
